language: node_js
node_js:
- 9
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: XV5LiTo4Zr9tR5AY7jeCrpqd+MyARs8UiopMq5ua0rug3su5cLzzA02Vib8XPn+qPws6FWj2ySh54SCBGCnHS9Ts3hEkNMfWe/igYVVmJ4W97hgB+CeGj9o9OorstdOO3jbj3ZgyXeF7hW7KG2RddlJma/9RidrJIjqB8ZERGbqTfzzvtY+xbx+RgU1NVmg5yWoYtFUmf0RKowSWSFh2CFK2IhQbuE6nyWRtME2lY2HxvZ5gdQVj99NUlwFrqspo1tmDnxofnasGte1IjkmfkpQpx7NxjMVhaUUlhNrmO0wWfcpKrHVjsobw6wJd+erF+WMGGfNVT5n8zVldSNeLyPdg/MvC091pg0edi0IZ54pz8tYd002q7uJIGb4eUYTJT0BgptGJnAAJwpII7WbQjPbL7lnwl6W5tddWpi8T8h+szkDRvusS7z2khkVFyPLGDHpT1eeFjr216TGjeAHF5VJ9avua0tbPWRgUEz7k9WXLO6ShJn45lbRkY23rbNHPTKuFHalWS5E9Toej3k+6ehs+mBI7UAzIo1LAwMrjDkatyMCRBQEquX4k6d+9fXSzQ8M8OgzOfyYOzBJl7cJSz7K+9WBUgPsG0qMzok+2n93uHK8VSTofzfNED2Q55n72tyECL1X0upU+eEjs6sSzi28R4h3GtZ204KeleNiZ2Xo=
