language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: Ol3kZpw/Hext616dfrVngWBIWsYgvOpPaJZ6AkUmNLy7E/iCC/XVurZNJoi2OyXeUf2tth8vbTWhLKe5Tz1+zG6MMIaJ48ur06B8M5Gt/pCeBt1a0Kfm9uLauW2Wraa/knf4y0PC7UJzyO2Clu12tKhggKljnGfJt78718u6rLCgJ2FWu9LPTl9mLYiKYDxMhAxb/mPTkzp4jMaENBsLdXuWVspws9L6Ft0C1mkxF3hFKzugGPF7zclX4MOYx0pvF38fscv6TUd+vNeTWxHP4DU0iQCJel8zExW0pTvuu8Hp85fiD7NplYYOXgAbkLPET4tzcdfcDM+5AgGs6w0IQ8uIHU4DlhKth0tgNN9YaH3CFGPbvG4KiLAHUP6Ig5aAVJCwrISMKws3gQ3bl2v8O522yqIGZo83AVvtfHdksZZMEJDyDV21pumFLsn4Y5x7cnlCS3FRWDm8DgZl1IS6lScSThskflvm3wSxq2tykRcS5XFVb3hPIV2o7EypqgJ2A+4uFGsvwqP0m2BTsVTtwYUMH4il3aumgVR6KaF4vl79jE8Y9o3GkZ3DHKS+HBEJx5ue/oNKlXEpii2SDK/ewq6eM3XoXsas+nMOz4rdGyM6TUOS9W6mKOMUrWK0R7tyN8/CVyT720aUuF8HaRYP09k5f6wVmxR5Vcfk2enZ6+I=
notifications:
  slack:
    secure: JfXj7en2jJydHAdLsPS3WRHHmbjFgDAUNRr21PSC5ifNhPA/6DQjzTlidV6R3GmJA1xZMbII7rWlfp8blezxypx+JWHtHsVJqqrlTmtDRLv4N1X5Kqn8EW/hZPL1P6N4c84xGmu80P94ACadjbLJuKI8lv7u3FQs/In3qJjJNPXAmyedHLB7h1/Cipxbv2WnWX731MQvwknHdqcDU8os0WMBPJ44SzNI/PrjRRj+xzPCOFbLkt1yUjl9KgGtCOPOP8gHKrhtYKe0TGg3bgPHyxRWjfYRC40ua0kIdOhxJMd3a4HdCu0XZavrXaZN+ZdIck8vge0WG2xk+103zCBpGVrrMGgAEAG11Npf9C/GFwK3aZ/IX8Xf+r1Awzw9+k34bPCKtJh5yoqoZE3kpd8LJWXLz8um/xSeIo9iXuz9yDxqKmbz4g/0xGG5b2ABuiOygqxXXWVUwzJitvFhjGITSDj2VMG54o01T8Jq4jRMrZZhJZ54nAIxTX3qK8kWSD508zOr7yKD63o6YKlLszHy02xufOfI7Sab9P8h6YgBHwyM6GTYddIKHgSVn/4bHa2V1oWs+FmnoA6Wfl59KKFOm5lqAPsUmQFLDMvP4ABmLdIPjCMDprKAxWa3bkhZr2gs0/utwyqi7oWGpEQ52DBn21SUSWo2qEvgibpyuQA3bnA=
deploy:
- provider: npm
  api_key:
    secure: kGq4BoDInCq08VgM64KY9gtdKpvY/8UCvbpMzBcdc1NE0wyzGq3D9LW1l9fb+Fbdv834uYEIUd/+CwB9kPlkfVOrzRd1CaGIqCj+hJJcO149t+cvHkHtRJlYGSFfsOd/Wv3OkH+YEA6ABYLAEsuhZ4r3HzULHs11SqBQlt3mO4WTB59EPoc1xpFQV/85kXzuPkvZ2a0yhQ3x534UR0Upzks39IkPwrBqgPc+3LYrOkYB7TmQi8ILhMgkqVaBLhRrn/GdYrRA6eXjzNkqXETgyfFfeqenM0idDr8iZXkadx3tWTiuLRwuATdqP1/vmEsqPn570LzO/cM/NLCzwZwFE+db/lFFM6fX5/sszHMURUhRtwHEffeIoLmNZbUMO3kHq4/iwyMIu3hGMrmmH0Rlw118KQ6/NITsW6hfNi+vbHe8fasEVK3XsOtvHSYlmwXbwOr/ODJ7nyCl84jA6cqqnQhzol0ML3fmSSGZV60ikk4k9A6TC346S0Hzok44ND7PjQndLTtbcUki1zxDM+LSgK3YrETFvfd0rpseynyJp174p2l12822mgyF47Ew2AZlZVuy4RVPqRPTBgJev9Onobj4cz5xmkX1RpZKC0DPXosPHmqMrcVifPBlVLdeGFstkae4Id+je70xhJvDtV8ThjWS/8Q+eoS5jp8AywKbOfA=
  email:
    secure: O/zZOzndC55eFJ70YHqtLxbaEciWJTGMUU/lqNcydEOBEXLrMtGmCf/yJZLGrt91WSqzREjbZBtk/s1EdHtbMc4mz/wS5VVPU526EC0qUeQ40Bpb9k5Wf4J4RM+pUKilzUSIZ4KPKw2Go5hmVEYwxXOBGUTPjjPmqlGcvtJT2XLK1b88ot5GMyE775a6v1BDApcknCWqqdxKMHcyr0zf2ZHhnt46jQpm8JEd+swqcclBgjBP4sA1nyXm52hfNPacTQh5oraxeLWY9A417bVZakObZ9IanXTGoZOY7a6NfGFshRwWWvgNn+uVRSR/Yvecm8mM56RUch7vdwNV3JO1ehIEetqxlUyZP9RrxlbiZdTudH31E63iSzVfeltFbprwvTEc/sFs+r6OoCLqbKtjRxMm2+TcI+H9f8cPBy1ScrXhB0pYnYDwn8WvnTvY4s4HP8prJ9KIezrkX0m0nid0/XdLe5O6Dvxb39NNywJBl2cEYLG88okwPQqLHQFaMCetIRlnRsI/A510lFcCjwjE+8inVFSJmfkjk+g4QcvZmdblD3FGjzuSlmaYrsMf456nsLpRvD3rWhKTbJmJgIbtTDMa9sDpuX1Wz8Cfod6iXAKGvfD9eRQDjHG8U4cvSr1355bgo7Mj7/UL+QLaWTvS7cirMq+hTWmSnIFLEJMt7Cs=
  on:
    branch: master
