language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: XV5LiTo4Zr9tR5AY7jeCrpqd+MyARs8UiopMq5ua0rug3su5cLzzA02Vib8XPn+qPws6FWj2ySh54SCBGCnHS9Ts3hEkNMfWe/igYVVmJ4W97hgB+CeGj9o9OorstdOO3jbj3ZgyXeF7hW7KG2RddlJma/9RidrJIjqB8ZERGbqTfzzvtY+xbx+RgU1NVmg5yWoYtFUmf0RKowSWSFh2CFK2IhQbuE6nyWRtME2lY2HxvZ5gdQVj99NUlwFrqspo1tmDnxofnasGte1IjkmfkpQpx7NxjMVhaUUlhNrmO0wWfcpKrHVjsobw6wJd+erF+WMGGfNVT5n8zVldSNeLyPdg/MvC091pg0edi0IZ54pz8tYd002q7uJIGb4eUYTJT0BgptGJnAAJwpII7WbQjPbL7lnwl6W5tddWpi8T8h+szkDRvusS7z2khkVFyPLGDHpT1eeFjr216TGjeAHF5VJ9avua0tbPWRgUEz7k9WXLO6ShJn45lbRkY23rbNHPTKuFHalWS5E9Toej3k+6ehs+mBI7UAzIo1LAwMrjDkatyMCRBQEquX4k6d+9fXSzQ8M8OgzOfyYOzBJl7cJSz7K+9WBUgPsG0qMzok+2n93uHK8VSTofzfNED2Q55n72tyECL1X0upU+eEjs6sSzi28R4h3GtZ204KeleNiZ2Xo=
notifications:
  slack:
    secure: C0a9V9JV9Qm5twEldnBzL96SG+cXIto6xg7jgyKINY4QBnHYVRLSl1XkdPYLb4TsR0HrzTHSmXqe+l07MAnWjzeGCua9JjfeBntxCxjA9I9wWgJ5Fskc2u2YGaNIVO5RepjhMHEFhYLvXued8eMbWjKEHH8bvP7qTAUnvAVr2Kh+amjr/JlJjsXKPKq+LC3qb/olzCPxyWS9dFZHRivz33YwXe8kwaiDH1OctW11208GGpOvn6cM/PJbVJQgyz8Ijj++mw+O+P0baS/uG2F0+83SUgmk+ewIklYNXvQIq8Zs10cGu8NoLMD0YtSNOh9i43r4uMHsc5CBFBqrqUTpMSBzQVX4Bfz3E1pbx9sR8SSImmUfXPilX8aSaPSmiMIw/Z3Th1ZtVUwaZ8tF4dkKb7xOusDgdn9J5qJzx5VdMUt+YQgrKRzdDSPn+T8qo8kEXbu85wDivb/RQgr215q85WfevEV7kki3G4SuFJPcLQceTJbw316nFLtPfGlZ4uRBQ/6Z4eZUhheamlSPNcQMO250AWJjjbnnV1eUw8Wsk5w7i61QPMmjf1E81Uq2cOzIIMWWt9C5MQjzaIAGQHpdYEYsVhEST2aHhkb0LdJwgN9t5VjCwV408jga/7FjC0otmGMSOH3xFY01DZgEhUDzlSj3J9GqIYD0zmLQ/ZzbOp4=
